# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hugo Affaticati
email: haffaticati@gmail.com
description: >-
  Welcome to the official site of Hugo Affaticati, AI expert and Cloud Infrastructure Engineer at Microsoft Azure.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_url: "https://www.linkedin.com/in/hugo-affaticati"  # Add your LinkedIn link
github_username: haffaticati

# Biography
biography: >-
  Hugo is a Cloud Infrastructure Engineer at Microsoft Azure, focusing on performance optimization and benchmarking AI systems. Over the past four years, he has served as the Technical Lead for the Microsoft Azure AI benchmarking team, pushing boundaries in AI infrastructure. His work is dedicated to making AI models more efficient and scalable, providing key insights into industry-standard models and their performance. Hugo has contributed to various white papers and articles, and actively participates in global AI conferences.

# Contact Section
contact_section: >-
  If you are interested in collaborating on AI-related projects, consulting opportunities, or conferences, feel free to reach out. I am open to discussing innovative AI infrastructure solutions, benchmarking practices, and ways to optimize large-scale AI systems. Please use the form below or email me directly at {{ site.email }}.

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

